config:
    aliass:
        1:
           command: awa  #este es el comando que se asa para ejecutar el alias
           usealias: true
           itemname: "&fAWA"
           useitem: true
           consume: true
           alias: say awa
           broadcast: false #si el mensaje es visible a todos los jugadores
           console: false
           sendmessagetoplayer: true
           message:
              - "line1"
              - "line2"
              - "line3"
           permission: none #si es none no se usara pero si es cualquier otra cosa si
        2:
           command: killall
           usealias: true
           alias: kill @p
           itemname: "&fAWA"
           useitem: false
           consume: false
           console: true #se ejecutara por consola
           broadcast: false #si el mensaje es visible a todos los jugadores
           sendmessagetoplayer: true
           message:
              - "line1"
              - "line2"
              - "line3"
           permission: none #si es none no se usara pero si es cualquier otra cosa si