main: rubrub07.simplealias.SimpleAlias
version: 0.0.2
author: rubrub07
softdepend: [PlaceholderAPI,NBTApi]
api-version: 1.16
name: SimpleAlias
commands:
   sahelp:
      description: Comando de ayuda de Simple Alias
   sareload:
      description: recarga el plugin