name: SimpleAlias
version: '${project.version}'
main: com.brecanyt.plugin.SimpleAlias
api-version: 1.18
depend: [ PlaceHolderApi ]
authors: [ BrecanYT ]
description: Simple alias plugin with papi support

commands:
  sahelp:
    description: Help command of SimpleAlias
  sareload:
    description: Reloads the plugin
